--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TR8697/Pocketmine-Hesapesle
build-by-default: true
branches:
- main-branch
projects:
  HesapEsle plugin:
    path: HesapEsle plugin/
...
